### ISSUE TITLE
Undefined index user_id (index.php line 367)

### ISSUE THREAD

**Issue by cmsmcq** [dhlab-epfl/dhwriter#13]
In the navigation bar at the left of the dhwriter.org home page, this morning I get an error message reading

Notice: Undefined index: user_id in /home/httpd/vhosts/dhwriter.org/httpdocs/index.php on line 367

I'm not entirely certain what ought to be appearing there where the error message appears.

**Comment by cyrilbornet** [comment]
should be fixed now.

**Comment by cmsmcq** [comment]
Confirming:  yes, appears to be fixed.
