### ISSUE TITLE
Conftool refuses pdf (Format Error)

### ISSUE THREAD

**Issue by gvasold** [dhlab-epfl/dhwriter#16]
A collegue had a problem yesterday uploading the review PDF generated by dhwriter to conftool. As I ran into the same issue today (conftool nags about bad format), I took a closer look on the PDF and found out that there were NUL-Bytes after  EOF. After removing them, conftools accepted my pdf. Just in case anyone else has the same problem ...

**Comment by cyrilbornet** [comment]
Hello,
Thanks a lot for your report. I contacted ConfTool this morning (as you can imagine, lots of people get this problem actually), and they also pretend out the NUL-bytes are faulty here.
Now the question is... where do this come from :-(
All I know is that it's quite hard to reproduce in test conditions, so it might be related to document sizes/complexity.
Any clue would be more than welcome :-)

**Comment by cyrilbornet** [comment]
OK, think I've got it.
The culprit seems to be Firefox's PDF plugin:
- Forcing the PDF to download seems to fix the problem on Firefox, at least.
- Problem couldn't be reproduced on any other browser anyway.
