### ISSUE TITLE
Review PDF not readable on Mac

### ISSUE THREAD

**Issue by mwidner** [dhlab-epfl/dhwriter#2]
The Review PDF generated is not readable on my Mac either with Adobe Acrobat Pro or with Preview. Both say the file is damaged: 

"Acrobat could not open <filename> because it is either not a supported file type or because the file has been damaged (for example, it was sent as an email attachment and wasn't correctly decoded)."

**Comment by cmsmcq** [comment]
When I downloaded the Review PDF, it arrived with a filename of abstract.pdf.html -- when I renamed the file, Preview agreed to open the file, but then displayed the same message described by mwidner.

When I open the file in Emacs, what I see is a fragment of HTML reading, in full:

```
<B>mPDF error: </B>Text contains invalid UTF-8 character(s)
```

**Comment by cyrilbornet** [comment]
This issue has been reported several times now, but I couldn't figure out where those UTF-8 characters are coming from yet. All I know is that it is not in the core of the texts, so either from the metadatas or (most probably) the bibliographies. Any clue about it would be more than welcome :-)

**Comment by cmsmcq** [comment]
Today, both the button labeled "PDF" and that labeled "review PDF" open PDF documents without incident in the browser.  (That is, I am now no longer able to replicate the problem.)  Perhaps the changes to the character escaping in the export made the difference.  So for my part, I think this bug can be closed.

**Comment by cyrilbornet** [comment]
Closed.
NB: not the same as #16
