### ISSUE TITLE
Summary included in exported PDF?

### ISSUE THREAD

**Issue by Tegomena** [dhlab-epfl/dhwriter#33]
When we are exporting our DH 2014 paper into PDF, the "Summary" from the metadata is included at the top. Due to the fact that our summary is identical with the "Introduction", we would like to ask if we have to write a new summary or if the summary is used in different locations and not printed at the top of the paper in the final proceedings?

**Comment by cyrilbornet** [comment]
Hi,
The summary on the top of the page is to be thought as a note for your reviewers and will normally not be included in the printed version of the final proceedings.
Yours,
