### ISSUE TITLE
Database dump for new installation?

### ISSUE THREAD

**Issue by airways** [dhlab-epfl/dhwriter#35]
We would like to use DHWriter for some internal documentation - do you have a database dump that we can use to get the program running? It seems to currently be impossible to install this on a new server since there is no mechanism to create the needed database schema.

**Comment by cyrilbornet** [comment]
Hi,
You're right, I still need to provide a functional setup script, didn't have the time to finish it yet, though...
Please contact me at - support@dhwriter.com - **support@dhwriter.org** and I'll send you a dump of the database structure.

Yours,

**Comment by airways** [comment]
Email sent, thanks!

**Comment by airways** [comment]
Er, actually the email bounced.

support@dhwriter.com: host spool.mail.gandi.net[217.70.184.6] said: 554 5.7.1
    support@dhwriter.com: Relay access denied (in reply to RCPT TO command)

**Comment by cyrilbornet** [comment]
support@dhwriter.org, sorry!

**Comment by airways** [comment]
Sent, thanks!
