### ISSUE TITLE
Angle brackets 

### ISSUE THREAD

**Issue by cmsmcq** [dhlab-epfl/dhwriter#4]
When a paragraph discussing markup practice mentions the 'p' element, it is not unusual for authors to write the element name using angle brackets.  In an XML document, the text of a paragraph discussing markup might thus include the character sequence blank, left-angle-bracket, p, right-angle-bracket, blank.

Nothing in the interface tells me to do anything special about such characters, and when I type them in (or copy and paste them from a text display elsewhere), they display as expected.  (It's possible that the introductory text did talk about this, but it seems to have become inaccessible once I logged in.)

But when I attempt to export HTML, or TEI, or PDF, I run into trouble if they are not escaped.

If I do escape them, using an entity reference for the 'lt' entity, they do not display nicely in the interactive display.

Ideally, an interface like this should take charge of escaping the left angle bracket and the ampersand symbol, allowing the user to type them like any other character -- unless your intent is to allow users to write their own markup in the interface, as if they were using vi or emacs.

**Comment by cyrilbornet** [comment]
Actually looking at the code the editor interface seems to behave correctly (HTML entities are converted when typed or pasted), but for some reason they seem to be decoded at export time.
This has to be fixed.
